#include <bits/stdc++.h>

using namespace std;

int n = 10, cnt, x, y;

void L() { --x, ++cnt, printf("L"); }
void R() { ++x, ++cnt, printf("R"); }
void U() { ++y, ++cnt, printf("U"); }
void D() { --y, ++cnt, printf("D"); }

void gen() {
    while (x != 11)
        R();
    D();
    while (x != 22)
        R();
    U();
    while (x != 11)
        L(); //(11, 0)
    while (y != 10)
        U(); //(11, 10)

    for (int i = 10; i > -10; i--) {
        if (x == 11) {
            while (x != -10)
                L(); //(-10, i)
            for (int j = 1; j <= n; j++)
                U(), L(), D();
            L(), D();
            while (x != -11)
                R(); //(-11, i - 1);
        } else {
            while (x != 10)
                R();
            for (int j = 1; j <= n; j++)
                U(), R(), D();
            R(), D();
            while (x != 11)
                L(); //(11, i - 1);
        }
    }

    D();
    while (x != -11)
        L();
    U();
    while (x != 0)
        R();
    D();
    while (x != 11)
        R();
    U(); // Everything at row -10, player at (11, -10)

    // I
    D(), L(), U(), R(), U(), L();
    D(), D(), L(), L(), U(), U(), U(), L(), U(), R();

    // O
    D(), D(), D(), D(), L(), L(), L(), U(), D(), L(), U(), D(), L(), U(), U(),
        U(), D(), R(), R();

    // I
    D(), D(), L(), L(), L(), L(), U(), R(), R();
    L(), L(), L(), U(), R(), R(), R();
    L(), U(), U(), R(), U(), R();

    printf("\n");
}

char S[] =
    "RRRRRRRRRRRDRRRRRRRRRRRULLLLLLLLLLLUUUUUUUUUULLLLLLLLLLLLLLLLLLLLLULDULDUL"
    "DULDULDULDULDULDULDULDLDRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRURDURDURDURDURDURDU"
    "RDURDURDURDRDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLULDULDULDULDULDULDULDULDULDULD"
    "LDRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRURDURDURDURDURDURDURDURDURDURDRDLLLLLLLLL"
    "LLLLLLLLLLLLLLLLLLLLLLULDULDULDULDULDULDULDULDULDULDLDRRRRRRRRRRRRRRRRRRRR"
    "RRRRRRRRRRRURDURDURDURDURDURDURDURDURDURDRDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL"
    "ULDULDULDULDULDULDULDULDULDULDLDRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRURDURDURDUR"
    "DURDURDURDURDURDURDRDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLULDULDULDULDULDULDULDU"
    "LDULDULDLDRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRURDURDURDURDURDURDURDURDURDURDRDL"
    "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLULDULDULDULDULDULDULDULDULDULDLDRRRRRRRRRRRR"
    "RRRRRRRRRRRRRRRRRRRURDURDURDURDURDURDURDURDURDURDRDLLLLLLLLLLLLLLLLLLLLLLL"
    "LLLLLLLLULDULDULDULDULDULDULDULDULDULDLDRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRURD"
    "URDURDURDURDURDURDURDURDURDRDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLULDULDULDULDUL"
    "DULDULDULDULDULDLDRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRURDURDURDURDURDURDURDURDU"
    "RDURDRDLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLULDULDULDULDULDULDULDULDULDULDLDRRRR"
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRURDURDURDURDURDURDURDURDURDURDRDLLLLLLLLLLLLLLL"
    "LLLLLLLLLLLLLLLLULDULDULDULDULDULDULDULDULDULDLDRRRRRRRRRRRRRRRRRRRRRRRRRR"
    "RRRRRURDURDURDURDURDURDURDURDURDURDRDLLLLLLLLLLDLLLLLLLLLLLLLLLLLLLLLLURRR"
    "RRRRRRRRDRRRRRRRRRRRUDLURULDDLLUUULURDDDDLLLUDLUDLUUUDRRDDLLLLURRLLLURRRLU"
    "URUR";

int main() {
    printf("%s\n", S);

    return 0;
}